module.exports = [
  {
    title: 'Asterank',
    desc: 'Crawl, visualize, and compute on all known asteroids',
    imgurl: 'http://i.imgur.com/5FI40mLl.jpg',
    url: 'http://www.asterank.com',
    press: [
      {
        source: 'foo bar',
        url: 'baz',
      },
    ],
  },
  {
    title: 'AdDetector',
    desc: 'Native ad detection. Spot articles with corporate sponsors.',
    imgurl: 'http://i.imgur.com/5XwQaQxl.png',
    url: 'http://www.ianww.com/ad-detector',
  },
  {
    title: 'Textbelt',
    desc: 'Free outgoing SMS API. Over 1M texts sent',
    imgurl: 'http://i.imgur.com/e1TyUkSl.png',
    url: 'http://textbelt.com',
  },
  {
    title: 'Galaxies',
    desc: '2 billion cubic light-years, based on one of the largest n-body simulations ever.',
    imgurl: 'http://i.imgur.com/mzwBJ8Sl.jpg',
    url: 'http://www.asterank.com/galaxies',
  },
  {
    title: 'Asteroid Viewer',
    desc: 'Accurate 3D models of asteroids from radar and inverted light curves.',
    imgurl: 'http://i.imgur.com/yQaQHiUl.png',
    url: 'http://www.ianww.com/asteroid-viewer',
  },
  {
    title: 'Dinosaur Pictures',
    desc: 'The official dinosaur picture database.',
    imgurl: 'http://i.imgur.com/p5cHTml.png',
    url: 'http://dinosaurpictures.org/',
  },
  {
    title: 'Ancient Earth',
    desc: 'What did Earth look like 600 million years ago?',
    imgurl: 'http://i.imgur.com/Ya57O3tl.png',
    url: 'http://dinosaurpictures.org/ancient-earth/',
  },
  {
    title: 'Harvest',
    desc: 'Aerial infrared crop monitoring. Disrupt hackathon winner (3 prizes).',
    imgurl: 'https://i.imgur.com/SJVfCEg.jpg',
    url: 'http://harvesters.club',
  },
  {
    title: 'Space Balloons',
    desc: 'Sending cameras and other things to near-space.',
    imgurl: 'http://i.imgur.com/9ngl1H5l.jpg',
    url: 'http://www.ianww.com/blog/2015/07/17/sending-a-potato-to-near-space/',
  },
  {
    title: 'RapChat',
    desc: 'The future of communication.',
    imgurl: 'http://i.imgur.com/MdbV70Tl.png',
    url: 'http://www.rapchat.us',
  },
  {
    title: 'The Space Potato',
    desc: 'Successful kickstarter for a potato-powered mission to near-space.',
    imgurl: 'http://i.imgur.com/aOy79oEl.jpg',
    url: 'http://spacepotato.org',
  },
  {
    title: 'Watchtower',
    desc: 'Competitive monitoring platform, LAUNCH hackathon winner.',
    imgurl: 'http://www.ianww.com/images/watchtower.png',
  },
  {
    title: 'Interview Club',
    desc: 'Taking the pain out of hiring. LAUNCH hackathon winner (5 prizes).',
    imgurl: 'http://i.imgur.com/MjKtbLEl.png',
    url: 'http://www.gointerview.club',
  },
  {
    title: 'Asterank Discover',
    desc: 'Crowdsourced asteroid discovery - quarter million images reviewed.',
    imgurl: 'http://www.ianww.com/images/asterank_discover.png',
    url: 'http://www.asterank.com/discover',
  },
  {
    title: 'Verified Facts',
    desc: 'A viral conspiracy theory generator.',
    imgurl: 'http://www.ianww.com/images/verifiedfacts.png',
    url: 'http://www.verifiedfacts.org',
  },
  {
    title: 'HonestMemo',
    desc: 'Internal company discussion forum and feedback tool.',
    imgurl: 'https://i.imgur.com/Jud7U7zl.png?1',
  },
  {
    title: 'Luna',
    desc: '3D interactive moon.',
    imgurl: 'http://i.imgur.com/xtmqQQAl.png',
    url: 'http://www.ianww.com/moonviz',
  },
  {
    title: 'Candid Candidates',
    desc: 'Where do politicians get their money? Seattle hackathon winner.',
    imgurl: 'http://i.imgur.com/C2QG9ZOl.png',
    url: 'http://github.com/typpo/political-annotations',
  },
  {
    title: 'Six Degrees of Bowie',
    desc: 'A graph of musical influencers.',
    imgurl: 'http://www.ianww.com/images/bowie.png',
  },
  {
    title: 'Pluto',
    desc: 'Pluto in 3D.',
    imgurl: 'https://i.imgur.com/M9lM5gQl.png',
    url: 'http://www.ianww.com/pluto',
  },
  {
    title: 'KeepDream',
    desc: 'Dream recording and text analysis.',
    imgurl: 'http://www.ianww.com/images/keepdream.png',
    url: 'http://www.keepdream.me',
  },
  {
    title: 'World of Loot',
    desc: 'Pinterest-style MMO wishlists.',
    imgurl: 'http://www.ianww.com/images/worldofloot.png',
    url: 'http://www.worldofloot.com',
  },
  {
    title: 'Chatalyst',
    desc: 'Taking the pain out of video chat.',
    imgurl: 'http://i.imgur.com/yyayOHTl.jpg',
    url: 'http://www.ianww.com/meteor-showers/perseids',
  },
  {
    title: 'Gilded Age',
    desc: 'Visualizations and NLP for Gilded-age newspapers.',
    imgurl: 'https://i.imgur.com/qZ1wxmJl.png',
    url: 'http://github.com/typpo/gilded-age',
  },
  {
    title: 'TalkThen',
    desc: 'Convenient conference and telephony app.',
    imgurl: 'http://i.imgur.com/aKCnbFRl.png',
  },
  {
    title: 'In 2015 Dollars',
    desc: 'Inflation data calculator.',
    imgurl: 'http://www.ianww.com/images/in2013dollars.png',
    url: 'http://www.in2013dollars.com',
  },
  {
    title: 'CodeNav',
    desc: 'Easily navigate code on Github. Keyword highlight, code search, etc.',
    imgurl: 'https://i.imgur.com/QJwU3Hzl.png',
    url: 'http://www.ianww.com/codenav',
  },
  {
    title: 'ListeningPost',
    desc: 'Contextual annotations for spoken conversation, YC Hacks winner.',
    imgurl: 'https://i.imgur.com/nwXZtDel.png',
  },
  {
    title: 'Ceres',
    desc: 'Ceres in 3D.',
    imgurl: 'https://i.imgur.com/Q3jcJiFl.png',
    url: 'http://www.ianww.com/ceres',
  },
  {
    title: 'Perseids',
    desc: 'Accurate model of the Perseids meteor shower.',
    imgurl: 'https://i.imgur.com/n5U34ahl.png',
    url: 'http://www.ianww.com/meteor-showers/perseids',
  },
  {
    title: 'Neutral Gas',
    desc: 'Micro carbon offsets for gas fill-ups.',
    imgurl: 'http://i.imgur.com/lSAUkmIl.png',
    url: 'https://www.neutralgas.com',
  },
  {
    title: 'Bunkmates',
    desc: 'AirBnB for hotels.',
    imgurl: 'http://i.imgur.com/oNx5JzAl.png',
  },
  {
    title: 'Gifthorse',
    desc: 'A gift suggestion engine.',
    imgurl: 'http://www.ianww.com/images/gifthorse.png',
    url: 'http://gifthorse.herokuapp.com',
  },
  {
    title: 'Room 77',
    desc: 'Better hotel search, acquired by Google.',
    imgurl: 'http://i.imgur.com/ua9nW9ol.png',
    url: 'http://room77.com',
  },
  {
    title: 'Planetary Resources',
    desc: 'Asteroid mining spacecraft and mission control software.',
    imgurl: 'https://i.imgur.com/PL95Da6.jpg',
    url: 'https://en.wikipedia.org/wiki/Planetary_Resources',
  },
  {
    title: 'Google',
    desc: 'Improving travel and local search.',
    imgurl: 'http://i.imgur.com/V2Js8Bwl.png',
    url: 'http://google.com',
  },
]
